# Generated by Django 5.1 on 2024-09-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0006_userprofile'),
    ]

    operations = [
    ]
