# Generated by Django 5.1 on 2024-09-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0007_merge_20240918_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
