# Generated by Django 5.1 on 2024-09-05 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_playlist_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlist',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
