# Generated by Django 5.1 on 2024-09-08 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mood',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('surprised', 'Surprised'), ('neutral', 'Neutral')], max_length=10),
        ),
    ]
