# Generated by Django 5.1 on 2024-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_remove_mood_created_at_mood_date_mood_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='notes',
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('angry', 'Angry'), ('surprised', 'Surprised')], max_length=10),
        ),
    ]
