# Generated by Django 5.1 on 2024-09-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_remove_mood_notes_alter_mood_date_alter_mood_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='user',
        ),
        migrations.AddField(
            model_name='mood',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(max_length=20),
        ),
    ]
