# Generated by Django 5.1 on 2024-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_alter_mood_mood_moodhistory_moodtracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodTracking',
        ),
    ]
