# Generated by Django 5.1 on 2024-09-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_remove_track_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
