# Generated by Django 5.1 on 2024-09-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_track_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio',
            field=models.URLField(default=''),
        ),
    ]
