# Generated by Django 5.1 on 2024-09-23 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_track_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio',
        ),
    ]
